apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mint-rollouts
  labels:
    codefresh.io/entity: component
    codefresh.io/internal: "false"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: csdp
  source:
    chart: argo-rollouts
    repoURL: https://codefresh-io.github.io/argo-helm
    targetRevision: 2.22.1-1-cap-sw
    helm:
      releaseName: argo-rollouts
  destination:
    namespace: default
    server: https://shclub.synology.me:6443
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
